import React from 'react'

const Welcome = () => {
  return (
    <div className="min-h-screen bg-gray-900 text-white flex flex-col items-center justify-center">
      <h1 className="text-6xl font-bold mb-4">Da Vinci 2</h1>
      <p className="text-lg text-center max-w-lg mx-auto mb-10">Imagination at your fingertips. Create, explore, and share unique images generated by AI.</p>
    </div>
  )
}

export default Welcome


